name: Trigger Site Rebuild on a CRON Schedule

on:
  schedule:
    - cron: "*/2 * * * *"
jobs:
  build:
    name: Log on console
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
